# Editor build failure reporter
# ========================================================
name: ðŸš¨ Report Building Failure
run-name: ðŸš¨ Report Building Failure (${{ inputs.imageTag }})

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag that failed to build"
        required: true
        default: "2017.4.30f1-webgl-1.0.0"

jobs:
  comment:
    name: ðŸ“ Report '${{ inputs.imageTag }}'
    runs-on: ubuntu-latest
    outputs:
      already-commented: ${{ steps.fc.outputs.comment-id != '' }}
    steps:
      - name: ðŸ” Find issue
        id: fi
        continue-on-error: true
        uses: micalevisk/last-issue-action@v2
        with:
          labels: failure report

      - name: âœ… Create issue
        uses: maxkomarychev/oction-create-issue@v0.7.1
        if: steps.fi.outputs.has_found == 'false'
        id: ci
        with:
          token: ${{ github.token }}
          title: "ðŸ”’ Failed building tags (editor) ðŸš¨"
          body: |
            This issue will be appended with image tags that failed to build.
            Image tags that fail more than once will be recorded to `.ignoreTags` file.
            They will be considered **"image tags to ignore."**
          labels: failure report

      - name: ðŸ” Find comment
        uses: peter-evans/find-comment@v3
        id: fc
        continue-on-error: true
        with:
          issue-number: ${{ steps.fi.outputs.issue-number }}${{ steps.ci.outputs.number }}
          comment-author: "mob-sakai"
          body-includes: ${{ inputs.imageTag }}

      - name: âœ… Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ steps.fi.outputs.issue-number }}${{ steps.ci.outputs.number }}
          body: |
            The build '${{ inputs.imageTag }}' failed.
            If it fails again, it will be added to the ignore list.

  ignore:
    name: ðŸš¨ Ignore '${{ inputs.imageTag }}'
    needs: comment
    if: needs.comment.outputs.already-commented == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: ðŸ“ Add the ignored image tag
        run: echo ${{ inputs.imageTag }} >> .ignoreTags

      - name: âœ… Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: ignore ${{ inputs.imageTag }}
          pull: --rebase --autostash
