name: ğŸ”– Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  release:
    name: ğŸ”– Release (${{ github.ref_name }})
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: write
    outputs:
      released: ${{ steps.release.outputs.new_release_published }}
    steps:
      - name: ğŸšš Checkout (${{ github.ref_name }})
        uses: actions/checkout@v4

      - name: ğŸ”– Run semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: |
          echo "ğŸ”– New release published: '${{ steps.release.outputs.new_release_published }}'" | tee -a $GITHUB_STEP_SUMMARY
          echo "ğŸ”– New release channel: '${{ steps.release.outputs.new_release_channel }}'" | tee -a $GITHUB_STEP_SUMMARY
          echo "ğŸ”– New release git tag: '${{ steps.release.outputs.new_release_git_tag }}'" | tee -a $GITHUB_STEP_SUMMARY

      - name: Dispatch 'Build All ğŸ› ï¸' workflow
        if: steps.release.outputs.new_release_published == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-all.yml
          ref: v${{ steps.release.outputs.new_release_version }}
